Navbar
ucsdkeebs/website pull request #16
Opened 2024-11-26 23:54 UTC by brandonmpark

2025-01-15 23:37 UTC, angela139 reviewed
Left some comments! You don't have to address them since you're inactive rn

2025-01-15 23:37 UTC, angela139 commented on src/components/Navbar/style.module.css
> +  transform: scale(1.1);
I don't like the transform; it's too whimsical for me

2025-01-15 23:37 UTC, angela139 commented on src/components/Navbar/index.tsx
> +        <span></span>
Why are there empty span tags?

2025-02-27 23:03 UTC, erhuang623 approved these changes
I agree that scaling a navbar up on hover is a little bit funny for a website

2025-02-27 23:15 UTC, erhuang623 requested changes
![image](https://github.com/user-attachments/assets/98f6ec4a-1b73-4433-b061-f5c66109ddcd)
It looks good and accurate to the figma! I would say just fix the responsiveness for mobile view with @media for devices with certain width/height.

2025-05-08 20:08 UTC, merged